version: '3.8'

services:
  consul:
    image: consul:1.16
    container_name: consul-dev
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0 -log-level=INFO
    volumes:
      - consul-data:/consul/data
    networks:
      - app-network

  nomad:
    image: nomad:1.6
    container_name: nomad-dev
    ports:
      - "4646:4646"
      - "4647:4647"
      - "4648:4648"
    environment:
      - NOMAD_DATA_DIR=/nomad/data
      - NOMAD_BIND_ADDR=0.0.0.0
    command: agent -dev -bind=0.0.0.0 -consul-address=consul:8500 -log-level=INFO
    volumes:
      - nomad-data:/nomad/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - consul
    networks:
      - app-network

  # Development databases (optional)
  postgres:
    image: postgres:15-alpine
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=servicesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  consul-data:
  nomad-data:
  postgres-data:
  redis-data:

networks:
  app-network:
    driver: bridge
