name: CI/CD for Calendar Service

on:
  push:
    branches: [ "main" ]
    paths:
      - "calendar/**"
      - ".github/workflows/calendar-ci.yml"
      - "nomad/calendar.hcl"
      - "docker/Dockerfile.stage"

env:
  IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
  DOCKER_IMAGE: friendy21/calendar-service
  SERVICE_NAME: calendar-service
  SERVICE_PORT: 5002

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./calendar
        file: ./docker/Dockerfile.stage
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Nomad
      run: |
        # Clean up any existing nomad files/directories
        sudo rm -rf /usr/local/bin/nomad
        sudo rm -rf nomad
        rm -f nomad.zip LICENSE.txt
        
        # Download Nomad
        curl -fsSL -o nomad.zip https://releases.hashicorp.com/nomad/1.8.3/nomad_1.8.3_linux_amd64.zip
        
        # Extract with overwrite flag
        unzip -o nomad.zip
        
        # Move the binary to /usr/local/bin
        chmod +x nomad
        sudo mv nomad /usr/local/bin/nomad
        
        # Clean up
        rm -f nomad.zip LICENSE.txt
        
        # Verify installation
        which nomad
        nomad version

    - name: Deploy to Nomad
      env:
        NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
        NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      run: |
        # Replace placeholders
        sed -i "s|IMAGE_TAG_PLACEHOLDER|${{ env.IMAGE_TAG }}|g" nomad/calendar.hcl
        sed -i "s|DOCKER_IMAGE_PLACEHOLDER|${{ env.DOCKER_IMAGE }}|g" nomad/calendar.hcl
        
        # Validate job
        if ! nomad job validate nomad/calendar.hcl; then
          echo "❌ Job validation failed"
          cat nomad/calendar.hcl
          exit 1
        fi
        
        # Run the job
        echo "🚀 Deploying calendar-service..."
        nomad job run nomad/calendar.hcl
        
        # Wait for deployment
        echo "⏳ Waiting for deployment..."
        MAX_ATTEMPTS=30
        ATTEMPT=0
        
        while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
          STATUS=$(nomad job status calendar-service 2>/dev/null | grep "^Status" | awk '{print $3}' || echo "pending")
          echo "Status check $((ATTEMPT + 1))/$MAX_ATTEMPTS: $STATUS"
          
          if [ "$STATUS" = "running" ]; then
            echo "✅ Calendar service is running!"
            nomad job status calendar-service
            exit 0
          elif [ "$STATUS" = "dead" ] || [ "$STATUS" = "failed" ]; then
            echo "❌ Deployment failed with status: $STATUS"
            nomad job status calendar-service
            exit 1
          fi
          
          sleep 10
          ATTEMPT=$((ATTEMPT + 1))
        done
        
        echo "❌ Deployment timed out after $((MAX_ATTEMPTS * 10)) seconds"
        nomad job status calendar-service || true
        exit 1

---

name: CI/CD for OneDrive Service

on:
  push:
    branches: [ "main" ]
    paths:
      - "onedrive/**"
      - ".github/workflows/onedrive-ci.yml"
      - "nomad/onedrive.hcl"
      - "docker/Dockerfile.stage"

env:
  IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
  DOCKER_IMAGE: friendy21/onedrive-service
  SERVICE_NAME: onedrive-service
  SERVICE_PORT: 5003

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./onedrive
        file: ./docker/Dockerfile.stage
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Nomad
      run: |
        # Clean up any existing nomad files/directories
        sudo rm -rf /usr/local/bin/nomad
        sudo rm -rf nomad
        rm -f nomad.zip LICENSE.txt
        
        # Download Nomad
        curl -fsSL -o nomad.zip https://releases.hashicorp.com/nomad/1.8.3/nomad_1.8.3_linux_amd64.zip
        
        # Extract with overwrite flag
        unzip -o nomad.zip
        
        # Move the binary to /usr/local/bin
        chmod +x nomad
        sudo mv nomad /usr/local/bin/nomad
        
        # Clean up
        rm -f nomad.zip LICENSE.txt
        
        # Verify installation
        nomad version

    - name: Deploy to Nomad
      env:
        NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
        NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      run: |
        sed -i "s|IMAGE_TAG_PLACEHOLDER|${{ env.IMAGE_TAG }}|g" nomad/onedrive.hcl
        sed -i "s|DOCKER_IMAGE_PLACEHOLDER|${{ env.DOCKER_IMAGE }}|g" nomad/onedrive.hcl
        
        nomad job validate nomad/onedrive.hcl
        nomad job run nomad/onedrive.hcl
        
        # Wait for deployment
        MAX_ATTEMPTS=30
        ATTEMPT=0
        
        while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
          if nomad job status onedrive-service 2>/dev/null | grep -q "Status.*running"; then
            echo "✅ OneDrive service is running!"
            break
          fi
          sleep 10
          ATTEMPT=$((ATTEMPT + 1))
        done
        
        if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
          echo "❌ Deployment timed out"
          exit 1
        fi
        
        echo "✅ OneDrive service deployed!"

---

name: CI/CD for Outlook Service

on:
  push:
    branches: [ "main" ]
    paths:
      - "outlook/**"
      - ".github/workflows/outlook-ci.yml"
      - "nomad/outlook.hcl"
      - "docker/Dockerfile.stage"

env:
  IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}
  DOCKER_IMAGE: friendy21/outlook-service
  SERVICE_NAME: outlook-service
  SERVICE_PORT: 5004

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./outlook
        file: ./docker/Dockerfile.stage
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Nomad
      run: |
        # Clean up any existing nomad files/directories
        sudo rm -rf /usr/local/bin/nomad
        sudo rm -rf nomad
        rm -f nomad.zip LICENSE.txt
        
        # Download Nomad
        curl -fsSL -o nomad.zip https://releases.hashicorp.com/nomad/1.8.3/nomad_1.8.3_linux_amd64.zip
        
        # Extract with overwrite flag
        unzip -o nomad.zip
        
        # Move the binary to /usr/local/bin
        chmod +x nomad
        sudo mv nomad /usr/local/bin/nomad
        
        # Clean up
        rm -f nomad.zip LICENSE.txt
        
        # Verify installation
        nomad version

    - name: Deploy to Nomad
      env:
        NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
        NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
      run: |
        sed -i "s|IMAGE_TAG_PLACEHOLDER|${{ env.IMAGE_TAG }}|g" nomad/outlook.hcl
        sed -i "s|DOCKER_IMAGE_PLACEHOLDER|${{ env.DOCKER_IMAGE }}|g" nomad/outlook.hcl
        
        nomad job validate nomad/outlook.hcl
        nomad job run nomad/outlook.hcl
        
        # Wait for deployment
        MAX_ATTEMPTS=30
        ATTEMPT=0
        
        while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
          if nomad job status outlook-service 2>/dev/null | grep -q "Status.*running"; then
            echo "✅ Outlook service is running!"
            break
          fi
          sleep 10
          ATTEMPT=$((ATTEMPT + 1))
        done
        
        if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
          echo "❌ Deployment timed out"
          exit 1
        fi
        
        echo "✅ Outlook service deployed!"
